---
title: "Project Goals"
---

This project aims to produce and showcase a simple data-driven investment strategy (glide path) an individual can leverage in retirement or non-retirement contexts.

## Core Assumptions

- While a complex set of diverse assets may be optimal, I assume a combination of index funds tracking merely U.S. equities, U.S. (intermediate-duration) bonds, and U.S. (short-duration) treasuries is sufficient to form a reasonably performant portfolio. In a taxable brokerage account, this would correspond to something like a portfolio of only `VOO`, `AGG`, and `SGOV`, respectively.
- Glide paths tested in this project potentially change or rebalance allocations exactly annually. This project does not aim to test favorable frequent-trading strategies.
- An investment strategy is considered "better" here if it yields higher expected returns under downside outcomes. See [Dataset and Simulation Strategy] for the exact mathematical framing.
- Optimal allocations in this project are glide paths, not fixed portfolios. It is assumed an investor should tolerate a constant level of "risk" at every remaining time period throughout the investment horizon, which naturally produces less aggressive investments closer to liquidiation.
- Optimal allocation is considered to only be a function of investment horizon or age. Individual circumstances like current wealth are not accounted for.

### Retirement-Specific Assumptions

- Retirement is assumed to occur at age 65, at which point 3.5% (more on this number in [Core Findings](core_findings.qmd)) of the real balance is withdrawn annually until age 90. I'll likely make these choices configurable in the [web app](web_app.qmd) since they vary substantially by investor.
- Modeling includes constant real annual contributions, starting at age 20 and ending at age 64. A potential future direction would be to model typical salary increases throughout one's career, since this is unlikely to involve constant contributions.

### Non-Retirement Assumptions

- Modeling involves an initial lump-sum investment with no further contributions, which is liquidated in full at the end of the investment period.
- Taxes and fees are not modeled, and assets are assumed to be highly (infinitely) liquid when rebalancing or re-allocation occur.
